### PR TITLE
Bug 1248277 - Add a User Agent to requests made to Treeherder

### PR DESCRIPTION
**Pull request by edmorley**
https://bugzilla.mozilla.org/show_bug.cgi?id=1248277

### CODE REVIEW

**Comment by sydvicious** [comment]
@edmorley r+

**Comment by edmorley** [comment]
I don't have permissions for this repo, would you mind merging this for me at some point?
Many thanks :-)

**Comment by sydvicious** [comment]
@edmorley Done

**Comment by edmorley** [comment]
Thank you :-)

**Pull request merged**
